server:
  port: 9000
  context-path: /

spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
    deserialization.fail-on-unknown-properties: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  session:
    key: BOARD_SESSION_KEY

mail:
  protocol: smtp
  host: smtp.gmail.com
  port: 587
  encoding: UTF-8
  username: dev.godong9@gmail.com
  password: testmail
  debug: true
  smtp:
    start-tls-enable: true
    auth: true

---

spring:
  profiles: local
  datasource:
    username: test
    password: test
    url: jdbc:mysql://localhost/board?useUnicode=true&characterEncoding=utf8&useSSL=false

